# GitHub Sponsors
github: [kirabian] # ganti dengan username GitHub kamu

# Patreon
patreon: kirabian

# Open Collective
open_collective: kirabian

# Ko-fi
ko_fi: kirabian

# Tidelift (paket npm/pypi/composer dll)
tidelift: npm/kirabian

# Community Bridge
community_bridge: kirabian

# Liberapay
liberapay: kirabian

# IssueHunt
issuehunt: kirabian

# LFX Crowdfunding
lfx_crowdfunding: kirabian

# Polar
polar: kirabian

# Buy Me a Coffee
buy_me_a_coffee: kirabian

# Thanks.dev
thanks_dev: kirabian

# Custom sponsorship links (Indonesia biasanya pakai Trakteer / Saweria)
custom: ['https://trakteer.id/kirabian', 'https://saweria.co/kirabian']
